//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounthistory
    {
        public string patientID { get; set; }
        public string lastlogindate { get; set; }
        public string lastlogintime { get; set; }
        public string browser { get; set; }
        public string ipaddress { get; set; }
        public int accountID { get; set; }
    }
}
