//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedTime
    {
        public int Booked_ID { get; set; }
        public string ApptColumn { get; set; }
        public string ApptTime { get; set; }
        public Nullable<System.DateTime> apptDate { get; set; }
    }
}
