//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctoruser
    {
        public string Title { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
        public string PrimarySpeciality { get; set; }
        public string BoardCertified { get; set; }
        public string YearsInPractice { get; set; }
        public string NPI_NO { get; set; }
        public string stateLicense { get; set; }
        public string otherLicense { get; set; }
        public string cellno { get; set; }
        public string Skype { get; set; }
        public string Address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string gender { get; set; }
        public string dob { get; set; }
        public string referredby { get; set; }
        public string isActive { get; set; }
        public int doctorID { get; set; }
    }
}
