//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorRoom
    {
        public DoctorRoom()
        {
            this.SeeDoctorNows = new HashSet<SeeDoctorNow>();
            this.PendingAppointments = new HashSet<PendingAppointment>();
        }
    
        public int ProviderID { get; set; }
        public string ColID { get; set; }
    
        public virtual ICollection<SeeDoctorNow> SeeDoctorNows { get; set; }
        public virtual ICollection<PendingAppointment> PendingAppointments { get; set; }
    }
}
