//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeeDoctorNow
    {
        public int ApptID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public int ProviderID { get; set; }
        public string ApptDate { get; set; }
        public string ApptTime { get; set; }
        public string ApptType { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string Feedack { get; set; }
    
        public virtual DoctorRoom DoctorRoom { get; set; }
        public virtual SeeDoctorNow SeeDoctorNow1 { get; set; }
        public virtual SeeDoctorNow SeeDoctorNow2 { get; set; }
    }
}
